--
-- Script generated by Schema Compare for Oracle 4.0.4.167 on 07/12/2017 20:43:31
--
SET DEFINE OFF

CREATE TABLE doerte_prod.importantdata (
  column1 VARCHAR2(20 BYTE)
);

CREATE TABLE doerte_prod.myfirsttable (
  column1 VARCHAR2(20 BYTE)
);

