CREATE OR REPLACE TRIGGER doerte_dev.DAVIDTABLE_TRG 
BEFORE INSERT ON doerte_dev.DAVIDTABLE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT DAVIDTABLE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/